### ISSUE TITLE
最新のAWSIM.zipがダウンロードできない（０バイト？）

### ISSUE THREAD

**Issue by seigot** [AutomotiveAIChallenge/aichallenge2023-racing#18]
既出であればすみません＆計画があれば申し訳ないのですが、
最新のAWSIM.zipがダウンロードできない（０バイト？）のようなのでissueをあげてみます。

https://automotiveaichallenge.github.io/aichallenge2023-racing/setup/index.html#画面録画の方法
> [GoogleDrive](https://drive.google.com/drive/folders/1EjgBxB_x0_xRla7_FdPaeEkiOU3vxW7e)から最新のAWSIM.zipをダウンロードし、aichallenge2023-racing/docker/aichallenge内に大会用AWSIM実行ファイルを展開

**Comment by taikitanaka3** [comment]
@seigot 

報告ありがとうございます。以下のリンクでアクセス権を付させていただきました。
他の方に関しましては一旦明日までアクセス権がない方は適宜申請いただく形を取ろうと思います。

明日フォルダのファイルを有効なものに入れ替えておいた状態にしておく予定です。

https://drive.google.com/drive/folders/1_Rynq8m8aJe9RiJwljWg5hLgTZQV47wG

**Comment by taikitanaka3** [comment]
https://github.com/AutomotiveAIChallenge/aichallenge2023-racing/tree/main/docker%2Faichallenge%2Faichallenge_ws%2Fsrc%2Faichallenge_submit%2Fdallara_interface%2Fdallara_launch%2Fdallara_launch%2Fmap

こちらのmapをmapfileのフォルダにコピーすると動作すること確認できました。

こちらもアップデート予定です。

**Comment by seigot** [comment]
ありがとうございます！

**Comment by taikitanaka3** [comment]
[AWSIMのbinaryのupdate](https://drive.google.com/drive/folders/1EjgBxB_x0_xRla7_FdPaeEkiOU3vxW7e) 完了しました。
ご報告ありがとうございました。
