### ISSUE TITLE
GPUありのケースでAWSIMとAutowareの速度表記単位が一致しない

### ISSUE THREAD

**Issue by MasanoriSuda** [AutomotiveAIChallenge/aichallenge2023-racing#25]
計画中であれば申し訳ありませんが、タイトルの件slackで確認したところ影響ありとのことでしたのでissueをあげさせていただきます。

GPUありのケースで速度の表記単位が一致しておりません。
・AWSIM：mph
・Autoware：km/h

![Screenshot from 2023-11-22 00-05-48](https://github.com/AutomotiveAIChallenge/aichallenge2023-racing/assets/45743821/6b65a199-b64e-4666-9696-7f63fd5d15da)

**Comment by MasanoriSuda** [comment]
slackでやりとししAWSIMの速度表示単位はmphのままでよいことを確認しました。
また、最新環境で粗動作を行いAWSIMとAutowareの速度が一致していることも確認しました。(1mph=約1.6km)
![Screenshot from 2023-11-23 09-28-52](https://github.com/AutomotiveAIChallenge/aichallenge2023-racing/assets/45743821/db357942-014a-4d42-9f53-9409f8e1d14b)

**Comment by taikitanaka3** [comment]
@MasanoriSuda 
検証ありがとうございました
