### ISSUE TITLE
ジャッジサーバ提出後に無限待ちが発生する問題の対策用

### ISSUE THREAD

**Issue by seigot** [AutomotiveAIChallenge/aichallenge2023-racing#60]
- 現象
ジャッジサーバ提出後にシミュレーション中が続く現象が起きることがある（8hくらいずっとシミュレーション中になり続ける）
おそらく正常系は問題なく、異常系の限定条件下で発生すると思われる。

- 原因仮説

以下で無限待ちしている可能性を考えています。
例えば何らかのエラーによりautowareが起動せず、そもそもresult.jsonが生成されないと無限待ちになる可能性を考えています。
https://github.com/AutomotiveAIChallenge/aichallenge2023-racing/blob/main/docker/evaluation/main.bash

```
# Wait result.js
echo “Wait for result.json”
until [ -f ~/awsim-logs/result.json ]
do
  sleep 5
done
```

- 対策案

"25minで設定し結果が出力されない場合にループを抜ける処理"案を対策案として検討する。
　実現案としては、例えばtimeoutを設けたり、待ち時間上限をカウントする等すれば解決する可能性がある。
（手元でちゃんとチェックしていれば発生しないかもしれないが、システム的に防げると望ましそうであるので対策検討する、、
　   1/31提出〆直前に発生すると手間がかかるので事前に対策して置けると望ましい、、はず）

**Comment by seigot** [comment]
流派が分かれそうな所ではありますが、以下のようなカウント用変数を設ける方式を提案します。
（一見すると愚直に見えるかもしれませんが、timeoutコマンドを使うより変更範囲が小さくわかりやすいはず、
　クリティカルな部分なので気をつけたい心理が働いています）

```
# Wait result.js
echo "Wait for result.json"
COUNT=0
until [ -f ~/awsim-logs/result.json ]
do
  if [ $COUNT -ge 240 ]; then
     echo "timeout count: $COUNT"
     break
  fi
  sleep 5
  ((COUNT+=1))
done
```

**Comment by seigot** [comment]
メモ：後ほど動作確認してpullrequestを投げる

**Comment by taikitanaka3** [comment]
@seigot 
ありがとうございます。大変助かります。

こちらカウントは以下の理由で1200（20分）が良いかなと思いました。
*awsimのタイムアウトが10分のため
*awsの強制シャットダウンが30分で走るため

@waterfallmouse 
コメントなどあればよろしいお願いいたします。

**Comment by seigot** [comment]
意図的にautowareを起動失敗させ（モジュールを１つ意図的に抜き出して）、無限待ちを再現して確認しました。
上記に加えてもう１点無限待ちになる箇所がありました。

https://github.com/AutomotiveAIChallenge/aichallenge2023-racing/blob/main/docker/evaluation/main.bash

```
# Waiting for Service Launch
until (ros2 service type /debug/service/capture_screen) 
do 
    echo "Waiting for Service Launch"
done

# Start Recording Rviz2
ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger

...

# Stop Recording Rviz2
ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger
```

- エラーログ
`ros2 service type /debug/service/capture_screen`が空振り続けたり、
`ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger`が応答待ち（応答は返ってこない）になると無限待ちです。

```
Launch user Autoware code
[ERROR] [ros2bag]: Output folder 'rosbag2_autoware' already exists.
Waiting for Service Launch
Waiting for Service Launch
Waiting for Service Launch
```

```
$ ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger
waiting for service to become available...
```

対策案
- 上記にもtimeout処理を加える（通常すぐ起動する部分と思うので、例えば３分timeoutを加える）
- `ros2 service call ...`時はコール前にチェックを１回はさむ、等です。

**Comment by seigot** [comment]
3点の変更をpullrequestしました！

１．以下にtimeout処理を追加
- 通常すぐ起動する部分だと思うので、timeoutを3分にしている。もしより望ましいtimeout値があれば変更可能です。
- timeout処理は、`COUNT`変数を用意して数える方式にしてみました。
`timeout`コマンドワンライナーと悩んだのですが、クリティカルな部分の変更のためシンプルでわかりやすいことを優先と考えた。

before

```
# Waiting for Service Launch
until (ros2 service type /debug/service/capture_screen) 
do 
    echo "Waiting for Service Launch"
done
```

after

```
# Waiting for Service Launch
 echo "Waiting for Service Launch"
 COUNT=0
 until (ros2 service type /debug/service/capture_screen) 
 do 
     if [ $COUNT -ge 36 ]; then
 	echo "timeout count: $COUNT"
 	break
     fi
     echo "Waiting for Service Launch"
     ((COUNT+=1))
     sleep 5
 done
```

２．以下に実行条件を追加
- `ros2 service type /debug/service/capture_screen`が空振りしているとここで無限待ちするため条件を追加して回避
（call可能であればcallする）
 
before 

```
# Start Recording Rviz2
ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger
...
# Stop Recording Rviz2
ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger
```

after

```
# Start Recording Rviz2
if ros2 service type /debug/service/capture_screen; then
     ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger
fi
...
# Stop Recording Rviz2
if ros2 service type /debug/service/capture_screen; then
     ros2 service call /debug/service/capture_screen std_srvs/srv/Trigger
fi
```


３．以下にtimeout処理を追加
- timeoutを20分にしている。もしより望ましいtimeout値があれば変更可能です。
- timeout処理は、１．同様に`COUNT`変数を使っています。

before

```
# Wait result.js
echo “Wait for result.json”
until [ -f ~/awsim-logs/result.json ]
do
  sleep 5
done
```

after

```
# Wait result.js
 echo "Wait for result.json"
 COUNT=0
 until [ -f ~/awsim-logs/result.json ]
 do
   if [ $COUNT -ge 240 ]; then
      echo "timeout count: $COUNT"
      break
   fi
   ((COUNT+=1))
   sleep 5
 done
```

補足・懸念事項
- 念の為、正常系（これまで同様に実行開始できること）異常系（エラー発生時に期待通りtimeout発生すること）の確認を10回づつ実行しました。動作確認は[自動実行スクリプト](https://qiita.com/seigot/items/55bde3cc77613eb3f2a1)が役立ちました。
ただサーバ側の動作確認は未です。影響ないように配慮したつもりなのですが、もし影響ありそうでしたらご指摘ください。
- 1日以上前にサーバへ提出したものが1/19現在も`2024-01-17 10:46 | シミュレーターテスト中`のままであり、キャンセル頂けると助かります。また、もしAWS側のtimeoutが存在している場合はtimeoutが効いてないのかも、、と思ったりもします。
（例えばアプリがFlutterで、例えば処理系がEC2 GPUインスタンスの場合、異常系で表示の更新ができていないのかもしれない等想いをはせていました）
- ここは流派がありそうなので（もっと効率的な方法があるとか）、即反映しない判断はありだとも思っています。

**Comment by taikitanaka3** [comment]
@seigot 
コメントと分析ありがとうございました。
> もしAWS側のtimeoutが存在している場合はtimeoutが効いてないのかも、、と思ったりもします。

ありがとうございます。期待する動作としてはAWS側のタイムアウトは存在しており、タイムアウトで終了しているのですが、その際のfront end側表示がシミュレータ実行中のままから遷移しないのが問題かと考察しているところです。

一方でresult．json以外のその他解析頂いた無限処理待ちが走る部分に関しては動画などのスコアボードへの記録を正しく残しておきたいという意図から、なるべくそのままにしておきたいです。

**Comment by seigot** [comment]
ご回答ありがとうございます、
以下の方針で対策できると効果的だと思いました、
私のpullrequestは反映せずそのままにする形でも全く問題ございません。

> もしAWS側のtimeoutが存在している場合はtimeoutが効いてないのかも、、と思ったりもします。
> 
> ありがとうございます。期待する動作としてはAWS側のタイムアウトは存在しており、タイムアウトで終了しているのですが、その際のfront end側表示がシミュレータ実行中のままから遷移しないのが問題かと考察しているところです。

（今回のようなエラー時に `front end側表示がシミュレータ実行中のままから遷移しない` が起きるメカニズムに興味がありますが、AWS EC2やVPCフローログ等にアクセスできず無念、、しかし少なくともEC2 GPUインスタンスがずっと稼働してる訳ではないとの事で安心いたしました。ずっと稼働してループしていたら大変申し訳ない気持ちでした..m(_ _)m）

**Comment by taikitanaka3** [comment]
https://jsae-aichallenge.slack.com/archives/C05S3AP4N6M/p1706415790141569
こちらで解決されました。また、再発した場合はre-opneお願いします。
